name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'Breaking'
    commit-types:
      - 'breaking'
  - title: 'Features'
    commit-types:
      - 'feat'
  - title: 'Bug Fixes'
    commit-types:
      - 'fix'
  - title: 'Documentation'
    commit-types:
      - 'docs'
  - title: 'Maintenance'
    commit-types:
      - 'chore'
      - 'ci'
      - 'build'
      - 'refactor'
      - 'style'
      - 'test'
      - 'perf'
