name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '* $TITLE ($URL) $SHA'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '⚠️ Breaking Changes'
    commit-types:
      - 'breaking'
  - title: '✨ New Features'
    commit-types:
      - 'feat'
  - title: '🐛 Bug Fixes'
    commit-types:
      - 'fix'
  - title: '📖 Documentation'
    collapse-after: 2
    commit-types:
      - 'docs'
  - title: '⚙️ Under the Hood'
    collapse-after: 2
    commit-types:
      - 'chore'
      - 'ci'
      - 'build'
      - 'refactor'
      - 'style'
      - 'test'
      - 'perf'
