name: 'Semantic PR Release Drafter'
description: 'Drafts your next release notes based on semantic commit messages from merged pull requests.'
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: edit-2
  color: orange
inputs:
  config-name:
    description: |
      If your workflow requires multiple release-drafter configs it be helpful to override the config-name.
      The config should still be located inside `.github` as that's where we are looking for config files.
    required: false
    default: 'release-drafter.yml'
  name:
    description: |
      The name that will be used in the GitHub release that's created or updated.
      This will override any `name-template` specified in your `release-drafter.yml` if defined.
    required: false
  tag:
    description: |
      The tag name to be associated with the GitHub release that's created or updated.
      This will override any `tag-template` specified in your `release-drafter.yml` if defined.
    required: false
  version:
    description: |
      The version to be associated with the GitHub release that's created or updated.
      This will override any version calculated by the release-drafter.
      Accepts inputs with or without the 'v' prefix ("1.2.3" or "v1.2.3", normalized internally).
    required: false
  publish:
    description: |
      A boolean indicating whether the release being created or updated should be immediately published.
    required: false
    default: ''
  latest:
    description: |
      A string indicating whether the release being created or updated should be marked as latest.
    required: false
    default: ''
  prerelease:
    description: |
      A boolean indicating whether the release being created or updated is a prerelease.
    required: false
    default: ''
  prerelease-identifier:
    description: |
      A string indicating an identifier (alpha, beta, rc, etc), to increment the prerelease version.
    required: false
    default: ''
  commitish:
    description: |
      The object that the release should be created to point to.
    required: false
    default: ''
  header:
    description: |
      A string that would be added before the template body.
    required: false
    default: ''
  footer:
    description: |
      A string that would be added after the template body.
    required: false
    default: ''
  name-template:
    description: |
      The template for the release name. Supports placeholders like $RESOLVED_VERSION.
      This will override any `name-template` specified in your config file.
    required: false
    default: ''
  tag-template:
    description: |
      The template for the release tag. Supports placeholders like $RESOLVED_VERSION.
      This will override any `tag-template` specified in your config file.
    required: false
    default: ''
  change-template:
    description: |
      The template for each changelog entry. Supports placeholders like $TITLE, $URL, $SHA, $NUMBER, $AUTHOR.
      This will override any `change-template` specified in your config file.
    required: false
    default: ''
  template:
    description: |
      The template for the release body. Supports placeholders like $CHANGES, $OWNER, $REPOSITORY, etc.
      This will override any `template` specified in your config file.
    required: false
    default: ''
  categories:
    description: |
      A YAML string defining the categories for grouping changes.
      Example:
        categories: |
          - title: 'Features'
            commit-types:
              - 'feat'
          - title: 'Bug Fixes'
            commit-types:
              - 'fix'
      This will override any `categories` specified in your config file.
    required: false
    default: ''
  category-template:
    description: |
      The template for category headers. Supports placeholders like $TITLE.
      This will override any `category-template` specified in your config file.
    required: false
    default: ''
  local-git-root:
    description: |
      Path to a local git repository root. When set, the action will use `git log`
      to fetch commits instead of the GitHub API. This is useful for integration testing.
      Note: Commit filtering is ancestry-based. When a base-ref-override is provided, the action
      uses git ancestry (for example, `git log BASE_REF..HEAD`) to find commits after that ref.
    required: false
    default: ''
  base-ref-override:
    description: |
      A git ref (tag, branch, or commit SHA) to use as the starting point for finding commits.
      When set along with local-git-root, the action will get commits that are descendants of this ref
      using git ancestry (for example, `git log BASE_REF..HEAD`).
      This also serves as the base version for calculating the next semver if base-version-override is not set.
      Format: git ref (e.g., "v1.0.0", "main", or a commit SHA).
    required: false
    default: ''
  base-version-override:
    description: |
      Override the base version to use for calculating the next version.
      When set, the action will skip querying the GitHub API for the last release
      and use this version as the starting point. Accepts inputs with or without the 'v' prefix ("1.0.0" or "v1.0.0", normalized internally).
      If base-ref is also provided, this takes precedence for version calculation.
    required: false
    default: ''
  dry-run:
    description: |
      A boolean indicating whether to run in dry-run mode.
      In dry-run mode, the action will calculate the release info and set outputs,
      but will not create or update any releases.
    required: false
    default: 'false'
  allow-major-bumps:
    description: |
      A boolean indicating whether to allow automatic major version bumps.
      When false (default), breaking changes will only bump the minor version,
      following "marketing-aware" semver semantics. When true, breaking changes
      will trigger a major version bump according to standard semver rules.
      Note: Pre-1.0 versions always bump minor for breaking changes regardless of this setting.
    required: false
    default: 'false'
  attach-files:
    description: |
      Files to attach to the draft release as assets. Accepts a single file path,
      a single glob pattern, or multiple file paths/globs as a newline-separated list.
      Supports standard glob patterns and brace expansion (e.g., dist/*.{whl,tar.gz}).
      Paths are resolved relative to GITHUB_WORKSPACE.

      When set, the action will:
      1. Delete ALL existing assets on the draft release (unless reset-files is false)
      2. Upload all matched files as release assets

      If the pattern matches zero files, the action will fail with an error.
      Requires GITHUB_TOKEN with contents: write permission.
    required: false
    default: ''
  reset-files:
    description: |
      Controls whether existing release assets are deleted before uploading new ones.
        - 'true': Delete all existing release assets (even if attach-files is not set).
        - 'false': Keep all existing release assets.
        - 'auto': Automatically delete existing assets if attach-files is provided,
          otherwise keep them.
    required: false
    default: 'auto'
outputs:
  id:
    description: The ID of the release that was created or updated.
  name:
    description: The name of the release
  tag-name:
    description: The name of the tag associated with the release.
  body:
    description: The body of the drafted release.
  html-url:
    description: The URL users can navigate to in order to view the release
  upload-url:
    description: The URL for uploading assets to the release, which could be used by GitHub Actions for additional uses, for example the @actions/upload-release-asset GitHub Action.
  major-version:
    description: The next major version number, with 'v' prefix removed (if applicable).
  minor-version:
    description: The next minor version number, with 'v' prefix removed (if applicable).
  patch-version:
    description: The next patch version number, with 'v' prefix removed (if applicable).
  resolved-version:
    description: The next resolved version number, based on semantic commit types, with 'v' prefix removed (if applicable).
