name: Demo Project Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  draft-release:
    name: Draft release (${{ matrix.package.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: existing-project
            config-name: release-drafter.yml
          - name: package-a
            config-name: release-drafter-package-a.yml
          - name: package-b
            config-name: release-drafter-package-b.yml

    steps:
      - uses: aaronsteers/semantic-pr-release-drafter@v1
        with:
          config-name: ${{ matrix.package.config-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
