name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - name: dummy-project/dummy-project-a
            config-name: release-drafter-dummy-project-a.yml
          - name: dummy-project/dummy-project-b
            config-name: release-drafter-dummy-project-b.yml
          - name: dummy-project/existing-project
            config-name: release-drafter-dummy-project-existing-project.yml
    name: Draft release (${{ matrix.release.name }})
    steps:
      - uses: actions/checkout@v4

      # Use local action (dogfooding)
      - uses: ./
        with:
          config-name: ${{ matrix.release.config-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The following config is commented out because it now matches the defaults.
        # It is kept here as an example of how to customize the action.
        # with:
        #   name-template: 'v$RESOLVED_VERSION'
        #   tag-template: 'v$RESOLVED_VERSION'
        #   template: |
        #     $CHANGES
        #
        #     ---
        #
        #     See also: [Full Release Notes ($RESOLVED_MAJOR_TAG.x family)](https://github.com/$OWNER/$REPOSITORY/releases?q=tag:$RESOLVED_MAJOR_TAG) | [Full Changelog ($PREVIOUS_TAG...$RESOLVED_TAG)](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_TAG)
        #   change-template: '* $TITLE ($URL) $SHA'
        #   categories: |
        #     - title: '⚠️ Breaking Changes'
        #       commit-types:
        #         - 'breaking'
        #     - title: '✨ New Features'
        #       commit-types:
        #         - 'feat'
        #     - title: '🐛 Bug Fixes'
        #       commit-types:
        #         - 'fix'
        #     - title: '▲ Other Changes'
        #       collapse-after: 2
        #       commit-types:
        #         - 'refactor'
        #         - 'perf'
        #         - 'style'
        #     - title: '📖 Documentation'
        #       collapse-after: 2
        #       commit-types:
        #         - 'docs'
        #     - title: '⚙️ Under the Hood'
        #       collapse-after: 2
        #       commit-types:
        #         - 'chore'
        #         - 'ci'
        #         - 'build'
        #         - 'test'
